coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 1%
        informational: true
    patch:
      default:
        target: 100%
        informational: false

comment: false
