# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/python@6.49.0)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# pylint: disable=wrong-import-position

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ._patch import *  # pylint: disable=unused-wildcard-import


from ._models import (  # type: ignore
    BodyAuthGetOidcToken,
    BodyAuthRevokeRefreshTokenByRefreshToken,
    BodyJobsRescheduleJobs,
    BodyJobsUnassignBulkJobsSandboxes,
    GroupInfo,
    HTTPValidationError,
    HeartbeatData,
    InitiateDeviceFlowResponse,
    InsertedJob,
    JobCommand,
    JobMetaData,
    JobStatusUpdate,
    Metadata,
    OpenIDConfiguration,
    SandboxDownloadResponse,
    SandboxInfo,
    SandboxUploadResponse,
    ScalarSearchSpec,
    SearchParams,
    SearchParamsSearchItem,
    SetJobStatusReturn,
    SetJobStatusReturnSuccess,
    SortSpec,
    SummaryParams,
    SummaryParamsSearchItem,
    SupportInfo,
    TokenResponse,
    UserInfoResponse,
    VOInfo,
    ValidationError,
    VectorSearchSpec,
)

from ._enums import (  # type: ignore
    ChecksumAlgorithm,
    JobStatus,
    SandboxFormat,
    SandboxType,
    ScalarSearchOperator,
    SortDirection,
    VectorSearchOperator,
)
from ._patch import __all__ as _patch_all
from ._patch import *
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "BodyAuthGetOidcToken",
    "BodyAuthRevokeRefreshTokenByRefreshToken",
    "BodyJobsRescheduleJobs",
    "BodyJobsUnassignBulkJobsSandboxes",
    "GroupInfo",
    "HTTPValidationError",
    "HeartbeatData",
    "InitiateDeviceFlowResponse",
    "InsertedJob",
    "JobCommand",
    "JobMetaData",
    "JobStatusUpdate",
    "Metadata",
    "OpenIDConfiguration",
    "SandboxDownloadResponse",
    "SandboxInfo",
    "SandboxUploadResponse",
    "ScalarSearchSpec",
    "SearchParams",
    "SearchParamsSearchItem",
    "SetJobStatusReturn",
    "SetJobStatusReturnSuccess",
    "SortSpec",
    "SummaryParams",
    "SummaryParamsSearchItem",
    "SupportInfo",
    "TokenResponse",
    "UserInfoResponse",
    "VOInfo",
    "ValidationError",
    "VectorSearchSpec",
    "ChecksumAlgorithm",
    "JobStatus",
    "SandboxFormat",
    "SandboxType",
    "ScalarSearchOperator",
    "SortDirection",
    "VectorSearchOperator",
]
__all__.extend([p for p in _patch_all if p not in __all__])  # pyright: ignore
_patch_sdk()
if TYPE_CHECKING:
    __all__.extend(
        [
            "DeviceFlowErrorResponse",        ]
    )
