# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class ChecksumAlgorithm(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Algorithms used to calculate sandbox checksums."""

    SHA256 = "sha256"


class JobStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Lifecycle statuses for a job."""

    SUBMITTING = "Submitting"
    RECEIVED = "Received"
    CHECKING = "Checking"
    STAGING = "Staging"
    WAITING = "Waiting"
    MATCHED = "Matched"
    RUNNING = "Running"
    STALLED = "Stalled"
    COMPLETING = "Completing"
    DONE = "Done"
    COMPLETED = "Completed"
    FAILED = "Failed"
    DELETED = "Deleted"
    KILLED = "Killed"
    RESCHEDULED = "Rescheduled"


class PilotStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Lifecycle statuses for a pilot agent."""

    SUBMITTED = "Submitted"
    WAITING = "Waiting"
    RUNNING = "Running"
    DONE = "Done"
    FAILED = "Failed"
    DELETED = "Deleted"
    ABORTED = "Aborted"
    UNKNOWN = "Unknown"


class SandboxFormat(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Archive formats supported for sandboxes."""

    TAR_BZ2 = "tar.bz2"
    TAR_ZST = "tar.zst"


class SandboxType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Sandbox Type."""

    INPUT = "input"
    OUTPUT = "output"


class ScalarSearchOperator(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Operators for comparing scalar search values."""

    EQ = "eq"
    NEQ = "neq"
    GT = "gt"
    LT = "lt"
    LIKE = "like"
    NOT_LIKE = "not like"
    REGEX = "regex"


class SortDirection(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Directions in which search results can be sorted."""

    ASC = "asc"
    DESC = "desc"


class VectorSearchOperator(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Operators for comparing values against a collection."""

    IN = "in"
    NOT_IN = "not in"
