# CI-specific values for testing gubbins
# Base gubbins configuration is in gubbins-charts/values.yaml
diracx:
  global:
    # Needed to be able to force pre-load the image in kind
    # see https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster
    # and https://iximiuz.com/en/posts/kubernetes-kind-load-docker-image/
    imagePullPolicy: IfNotPresent
