# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.5, generator: @autorest/python@6.4.11)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum

from azure.core import CaseInsensitiveEnumMeta


class Enum0(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Enum0."""

    AUTHORIZATION_CODE = "authorization_code"


class Enum1(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Enum1."""

    URN_IETF_PARAMS_OAUTH_GRANT_TYPE_DEVICE_CODE = "urn:ietf:params:oauth:grant-type:device_code"


class Enum2(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Response Type."""

    CODE = "code"


class Enum3(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Code Challenge Method."""

    S256 = "S256"


class Enum7(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Enum7."""

    ASC = "asc"


class Enum8(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Enum8."""

    DSC = "dsc"


class JobStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """An enumeration."""

    RUNNING = "Running"
    STALLED = "Stalled"
    KILLED = "Killed"
    FAILED = "Failed"
    RECEIVED = "RECEIVED"
    SUBMITTING = "Submitting"


class ScalarSearchOperator(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """An enumeration."""

    EQ = "eq"
    NEQ = "neq"
    GT = "gt"
    LT = "lt"
    LIKE = "like"


class VectorSearchOperator(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """An enumeration."""

    IN = "in"
    NOT_IN = "not in"
