diracx:
  developer:
    enabled: true
  diracx:
    hostname: gubbinsdiracx.example.com
    sqlDbs:
      dbs:
        LollygagDB:
        # --8<-- [start:my_pilots_helm_db]
        MyPilotDB:
        # --8<-- [end:my_pilots_helm_db]
  global:
    images:
      tag: "dev"
      services:
        repository: gubbins/services
      client:
        repository: gubbins/client
