diracx:
  developer:
    enabled: true
  diracx:
    hostname: gubbinsdiracx.example.com
    sqlDbs:
      dbs:
        LollygagDB:
  global:
    images:
      tag: "dev"
      services:
        repository: gubbins/services
      client:
        repository: gubbins/client
