# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.5, generator: @autorest/python@6.4.11)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum

from azure.core import CaseInsensitiveEnumMeta


class Enum0(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Enum0."""

    URN_IETF_PARAMS_OAUTH_GRANT_TYPE_DEVICE_CODE = (
        "urn:ietf:params:oauth:grant-type:device_code"
    )


class Enum1(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Enum1."""

    AUTHORIZATION_CODE = "authorization_code"


class Enum2(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Response Type."""

    CODE = "code"


class Enum3(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Code Challenge Method."""

    S256 = "S256"


class JobStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """An enumeration."""

    RUNNING = "Running"
    STALLED = "Stalled"
    KILLED = "Killed"
