# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/python@6.49.1)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# pylint: disable=wrong-import-position

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from diracx.client._generated.models._patch import *  # pylint: disable=unused-wildcard-import


from ._models import (  # type: ignore
    BodyAuthGetOidcToken,
    BodyAuthRevokeRefreshTokenByRefreshToken,
    BodyJobsRescheduleJobs,
    BodyJobsUnassignBulkJobsSandboxes,
    ExtendedMetadata,
    GroupInfo,
    HTTPValidationError,
    HeartbeatData,
    InitiateDeviceFlowResponse,
    InsertedJob,
    JobCommand,
    JobMetaData,
    JobStatusUpdate,
    OpenIDConfiguration,
    SandboxDownloadResponse,
    SandboxInfo,
    SandboxUploadResponse,
    ScalarSearchSpec,
    SearchParams,
    SearchParamsSearchItem,
    SetJobStatusReturn,
    SetJobStatusReturnSuccess,
    SortSpec,
    SummaryParams,
    SummaryParamsSearchItem,
    SupportInfo,
    TokenResponse,
    UserInfoResponse,
    VOInfo,
    ValidationError,
    VectorSearchSpec,
)

from ._enums import (  # type: ignore
    ChecksumAlgorithm,
    JobStatus,
    SandboxFormat,
    SandboxType,
    ScalarSearchOperator,
    SortDirection,
    VectorSearchOperator,
)
from diracx.client._generated.models._patch import __all__ as _patch_all
from diracx.client._generated.models._patch import *
from diracx.client._generated.models._patch import patch_sdk as _patch_sdk

__all__ = [
    "BodyAuthGetOidcToken",
    "BodyAuthRevokeRefreshTokenByRefreshToken",
    "BodyJobsRescheduleJobs",
    "BodyJobsUnassignBulkJobsSandboxes",
    "ExtendedMetadata",
    "GroupInfo",
    "HTTPValidationError",
    "HeartbeatData",
    "InitiateDeviceFlowResponse",
    "InsertedJob",
    "JobCommand",
    "JobMetaData",
    "JobStatusUpdate",
    "OpenIDConfiguration",
    "SandboxDownloadResponse",
    "SandboxInfo",
    "SandboxUploadResponse",
    "ScalarSearchSpec",
    "SearchParams",
    "SearchParamsSearchItem",
    "SetJobStatusReturn",
    "SetJobStatusReturnSuccess",
    "SortSpec",
    "SummaryParams",
    "SummaryParamsSearchItem",
    "SupportInfo",
    "TokenResponse",
    "UserInfoResponse",
    "VOInfo",
    "ValidationError",
    "VectorSearchSpec",
    "ChecksumAlgorithm",
    "JobStatus",
    "SandboxFormat",
    "SandboxType",
    "ScalarSearchOperator",
    "SortDirection",
    "VectorSearchOperator",
]
__all__.extend([p for p in _patch_all if p not in __all__])  # pyright: ignore
_patch_sdk()
if TYPE_CHECKING:
    __all__.extend(
        [
            "DeviceFlowErrorResponse",        ]
    )
