name: Record Changes Requested

on:
  pull_request_review:
    types: [submitted]

jobs:
  record:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.pull_request.number }}" > pr_number.txt
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: pr-info
          path: pr_number.txt
